#!/bin/sh
 
# Exit on error
set -e
 
# Source debconf library.
. /usr/share/debconf/confmodule
 
# Ask questions
db_input low vbox/vmuser || true
db_input low vbox/vmadmin || true
db_input low vbox/vmadminpass || true
 
# Show interface
db_go || true