#! /bin/bash

echo "postinst script"
# Source debconf library.
. /usr/share/debconf/confmodule
 
# Fetching configuration from debconf


#case $1 in 
#	configure)
#		db_get vbox/vmuser
#		VMUSER=$RET
#		 
#		db_get vbox/vmadmin
	#	VMADMIN=$RET
#		
#		db_get vbox/vmadminpass
#		VMADMINPASS=$RET
#		
#		sed -e "s/\(VMUSER=\)(.*)/\1$VMUSER/g" 
#	;;
#esac

#db_stop	
exit 0
